export const LOADING_STATUS = 'LOADING_STATUS'
export const SHOULD_REDIRECT = 'SHOULD_REDIRECT'
// FileUploadAction related
export const RESET_FILE_INPUT = 'RESET_FILE_INPUT'
export const FILEUPLOAD_HANDLE_CHANGE = 'FILEUPLOAD_HANDLE_CHANGE'

// TextareaAction related
export const TEXTAREA_HANDLE_CHANGE = 'TEXTAREA_HANDLE_CHANGE'