// RemoteWorker related
export const LOADING_STATUS = 'LOADING_STATUS';
export const SHOULD_REDIRECT = 'SHOULD_REDIRECT';
export const WORKER_DONE = 'WORKER_DONE';
export const WORKER_FAILED = 'WORKER_FAILED';
export const WORKER_RUNNING = 'WORKER_RUNNING';
export const UPDATE_WORKER_QUEUE_STATUS = 'UPDATE_WORKER_QUEUE_STATUS';
export const RESET_SESSION = 'RESET_SESSION';
export const UPDATE_WORKER_MESSAGES = 'UPDATE_WORKER_MESSAGES';

// FileUploadAction related
export const RESET_FILE_INPUT = 'RESET_FILE_INPUT';
export const FILEUPLOAD_HANDLE_CHANGE = 'FILEUPLOAD_HANDLE_CHANGE';
export const SET_UID = 'SET_UID';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const UPDATE_SUBMIT_STATUS = 'UPDATE_SUBMIT_STATUS';

// TextareaAction related
export const TEXTAREA_HANDLE_CHANGE = 'TEXTAREA_HANDLE_CHANGE';
export const RESET_TEXTAREA = 'RESET_TEXTAREA';
export const GENERATE_SAMPLE_INPUT = 'GENERATE_SAMPLE_INPUT';

// Option related
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const SELECT_OPTIONS = 'SELECT_OPTIONS';
export const RESET_SELECTED_OPTIONS = 'RESET_SELECTED_OPTIONS';
export const RESET_OPTIONS = 'RESET_OPTIONS';